// GENERATED by tools/generate_contract.py from the pydantic models in
// python/treeq_run_contract/. Do not edit by hand: CI runs
// `python tools/generate_contract.py --check` and fails on drift.
// Contract version 2.0.0.

export * from "./types.js";
export * from "./zod.js";

// The relational rules live beside the generated shapes because JSON
// Schema cannot express them; semantics.ts mirrors semantics.py and the
// shared fixture corpus is what proves the two agree.
export * from "./semantics.js";

// Root documents: RunReport
export const CONTRACT_VERSION = "2.0.0";
