// GENERATED by tools/generate_contract.py from the pydantic models in
// python/treeq_run_contract/. Do not edit by hand: CI runs
// `python tools/generate_contract.py --check` and fails on drift.
// Contract version 2.0.0.

/**
 * Where a declared physical property came from.
 *
 * There is deliberately no member for the file name. Reading a unit, a datum,
 * a CRS, a species or a wood density out of a file name is guessing, and this
 * enum is the mechanism that makes the guess unrepresentable: a producer that
 * wants to record "I got the species from the file name" has nothing valid to
 * write and must instead leave the declaration absent, which is the truth.
 */
export type DeclarationSource =
  | "operator"
  | "file_header"
  | "dataset_metadata"
  | "instrument_metadata";

/**
 * A declared coordinate reference system.
 *
 * Absent means nobody declared one. It does not mean WGS84, and no consumer
 * may substitute a default.
 */
export interface CrsDeclaration {
  readonly authority: string;
  readonly code: string;
  readonly source: DeclarationSource;
}

/**
 * Wood density, with where the number came from.
 *
 * A density is never a bare float in this contract. The pipeline does not
 * measure density, and the value chosen moves every mass it reports roughly
 * proportionally, so the reference travels with it.
 */
export interface DeclaredDensity {
  readonly value_g_cm3: number;
  readonly source: DeclarationSource;
  readonly reference: string;
}

/**
 * Whether the code ran. Says nothing about whether the result is usable.
 *
 * This axis and `QuantityStatus` are kept apart because they disagree in both
 * directions. A run that completes without raising can still produce a
 * diameter that no protocol will accept, and a run that fails partway can
 * still have produced usable measurements for the trees it reached.
 */
export type ExecutionStatus =
  | "ok"
  | "partial"
  | "failed";

/**
 * The unit the source file's coordinates are in.
 *
 * Required on every source declaration and never defaulted. A .ply carrying
 * millimetres and a .ply carrying metres are the same file extension, and the
 * difference is a factor of 1000 in every diameter this pipeline reports.
 */
export type LengthUnit =
  | "metre"
  | "centimetre"
  | "millimetre"
  | "foot"
  | "us_survey_foot";

/**
 * The named criteria a quantity was judged against.
 *
 * Mandatory on every `accepted` quantity. Without it, "accepted" is a bare
 * assertion; with it, a reader can fetch the criteria and disagree.
 */
export interface ProtocolRef {
  readonly id: string;
  readonly version: string;
  readonly criteria_uri?: string | null;
}

/**
 * Whether one derived number can be used, and under what claim.
 */
export type QuantityStatus =
  | "accepted"
  | "provisional"
  | "unusable";

/**
 * A range produced by varying an assumption, not a confidence interval.
 *
 * The low and high ends of this range come from recomputing the same number
 * at the ends of a plausible input range - in this pipeline, wood density.
 * That is not a 95% confidence interval and must never be relabelled as one:
 * it contains no sampling distribution, no error model for the measurement,
 * and no allowance for the allometric equation being wrong.
 *
 * The basis text is required, and a basis that claims an interval this range
 * is not is refused outright.
 */
export interface SensitivityRange {
  readonly low: number;
  readonly high: number;
  readonly basis: string;
}

/**
 * Why a quantity cannot be used.
 *
 * Required whenever a quantity is `unusable`, so the document always answers
 * "why not" without a reader having to reconstruct it from the logs.
 */
export type UnusableReason =
  | "dependency_missing"
  | "dependency_refused"
  | "dependency_unsupported"
  | "dependency_unusable"
  | "input_out_of_range"
  | "not_implemented"
  | "execution_failed"
  | "protocol_not_met";

/**
 * One derived number, its status, and what it was derived from.
 *
 * The `value`/`status` pairing is the contract's core rule:
 *
 * * `accepted` and `provisional` carry a value and a unit.
 * * `unusable` carries `value=None` and an `unusable_reason`.
 * * `value=0.0` is a real zero and is only ever written when the quantity
 *   really is zero. Missing is `None`, and the two are never interchanged.
 */
export interface Quantity {
  readonly value?: number | null;
  readonly unit: string;
  readonly status: QuantityStatus;
  readonly protocol?: ProtocolRef | null;
  readonly depends_on?: ReadonlyArray<string>;
  readonly unusable_reason?: UnusableReason | null;
  readonly basis?: string | null;
  readonly sensitivity?: SensitivityRange | null;
}

/**
 * Whether the code ran. Kept apart from whether the numbers are usable.
 */
export interface RunExecution {
  readonly status: ExecutionStatus;
  readonly started_at: string;
  readonly finished_at: string;
  readonly error_code?: string | null;
  readonly error_message?: string | null;
}

/**
 * Which code, which inputs, and how much of the input was actually used.
 */
export interface RunProvenance {
  readonly pipeline_version: string;
  readonly git_commit: string;
  readonly git_dirty: boolean;
  readonly algorithms: Readonly<Record<string, string>>;
  readonly wood_leaf_backend: string;
  readonly checkpoint_sha256?: string | null;
  readonly analysed_points_sha256: string;
  readonly n_source_points: number;
  readonly n_analysed_points: number;
}

/**
 * Container format of the uploaded point cloud, as declared.
 */
export type SourceFormat =
  | "ply"
  | "las"
  | "laz"
  | "txt"
  | "xyz"
  | "csv";

/**
 * The uploaded file and the physical facts that cannot be read off it.
 */
export interface SourceDeclaration {
  readonly file_name: string;
  readonly file_sha256: string;
  readonly byte_size: number;
  readonly format: SourceFormat;
  readonly length_unit: LengthUnit;
  readonly length_unit_source: DeclarationSource;
  readonly crs?: CrsDeclaration | null;
  readonly vertical_datum?: string | null;
}

/**
 * A declared species. Absent means unknown, never "assume something".
 */
export interface SpeciesDeclaration {
  readonly scientific_name: string;
  readonly source: DeclarationSource;
}

/**
 * Everything the pipeline was told before it ran.
 *
 * Nothing in here is derived from the file name. The properties a file name
 * is commonly abused to supply - unit, CRS, datum, species, density - are
 * either required with an explicit `DeclarationSource`, or optional and
 * genuinely absent when undeclared.
 */
export interface RunRequest {
  readonly contract_version?: string;
  readonly request_id: string;
  readonly source: SourceDeclaration;
  readonly species?: SpeciesDeclaration | null;
  readonly wood_density?: DeclaredDensity | null;
  readonly wood_leaf_backend: string;
  readonly protocol: ProtocolRef;
  readonly max_points?: number | null;
}

/**
 * One detected tree and every quantity derived for it.
 */
export interface TreeReport {
  readonly tree_id: number;
  readonly quantities: Readonly<Record<string, Quantity>>;
  readonly point_count: number;
  readonly species?: SpeciesDeclaration | null;
}

/**
 * The full, versioned result of one pipeline run.
 */
export interface RunReport {
  readonly contract_version?: string;
  readonly run_id: string;
  readonly request: RunRequest;
  readonly execution: RunExecution;
  readonly provenance: RunProvenance;
  readonly quantities?: Readonly<Record<string, Quantity>>;
  readonly trees?: ReadonlyArray<TreeReport>;
  readonly limitations?: ReadonlyArray<string>;
}

