// GENERATED by tools/generate_contract.py from the pydantic models in
// python/treeq_run_contract/. Do not edit by hand: CI runs
// `python tools/generate_contract.py --check` and fails on drift.
// Contract version 2.0.0.

import { z } from "zod";

export const DeclarationSourceSchema = z.enum(["operator", "file_header", "dataset_metadata", "instrument_metadata"]);

export const CrsDeclarationSchema = z
  .object({
    authority: z.string().min(1),
    code: z.string().min(1),
    source: DeclarationSourceSchema,
  })
  .strict();

export const DeclaredDensitySchema = z
  .object({
    value_g_cm3: z.number().lte(2.0).gt(0.0),
    source: DeclarationSourceSchema,
    reference: z.string().min(1),
  })
  .strict();

export const ExecutionStatusSchema = z.enum(["ok", "partial", "failed"]);

export const LengthUnitSchema = z.enum(["metre", "centimetre", "millimetre", "foot", "us_survey_foot"]);

export const ProtocolRefSchema = z
  .object({
    id: z.string().min(1),
    version: z.string().min(1),
    criteria_uri: z.string().nullable().optional(),
  })
  .strict();

export const QuantityStatusSchema = z.enum(["accepted", "provisional", "unusable"]);

export const SensitivityRangeSchema = z
  .object({
    low: z.number(),
    high: z.number(),
    basis: z.string().min(1),
  })
  .strict();

export const UnusableReasonSchema = z.enum(["dependency_missing", "dependency_refused", "dependency_unsupported", "dependency_unusable", "input_out_of_range", "not_implemented", "execution_failed", "protocol_not_met"]);

export const QuantitySchema = z
  .object({
    value: z.number().nullable().optional(),
    unit: z.string().min(1),
    status: QuantityStatusSchema,
    protocol: ProtocolRefSchema.nullable().optional(),
    depends_on: z.array(z.string()).optional(),
    unusable_reason: UnusableReasonSchema.nullable().optional(),
    basis: z.string().nullable().optional(),
    sensitivity: SensitivityRangeSchema.nullable().optional(),
  })
  .strict();

export const RunExecutionSchema = z
  .object({
    status: ExecutionStatusSchema,
    started_at: z.string().min(1),
    finished_at: z.string().min(1),
    error_code: z.string().nullable().optional(),
    error_message: z.string().nullable().optional(),
  })
  .strict();

export const RunProvenanceSchema = z
  .object({
    pipeline_version: z.string().min(1),
    git_commit: z.string().regex(new RegExp("^[0-9a-f]{40}$")),
    git_dirty: z.boolean(),
    algorithms: z.record(z.string(), z.string()),
    wood_leaf_backend: z.string().min(1),
    checkpoint_sha256: z.string().regex(new RegExp("^[0-9a-f]{64}$")).nullable().optional(),
    analysed_points_sha256: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    n_source_points: z.number().int().gte(0),
    n_analysed_points: z.number().int().gte(0),
  })
  .strict();

export const SourceFormatSchema = z.enum(["ply", "las", "laz", "txt", "xyz", "csv"]);

export const SourceDeclarationSchema = z
  .object({
    file_name: z.string().min(1),
    file_sha256: z.string().regex(new RegExp("^[0-9a-f]{64}$")),
    byte_size: z.number().int().gte(0),
    format: SourceFormatSchema,
    length_unit: LengthUnitSchema,
    length_unit_source: DeclarationSourceSchema,
    crs: CrsDeclarationSchema.nullable().optional(),
    vertical_datum: z.string().nullable().optional(),
  })
  .strict();

export const SpeciesDeclarationSchema = z
  .object({
    scientific_name: z.string().min(1),
    source: DeclarationSourceSchema,
  })
  .strict();

export const RunRequestSchema = z
  .object({
    contract_version: z.string().optional(),
    request_id: z.string().min(1),
    source: SourceDeclarationSchema,
    species: SpeciesDeclarationSchema.nullable().optional(),
    wood_density: DeclaredDensitySchema.nullable().optional(),
    wood_leaf_backend: z.string().min(1),
    protocol: ProtocolRefSchema,
    max_points: z.number().int().gte(1).nullable().optional(),
  })
  .strict();

export const TreeReportSchema = z
  .object({
    tree_id: z.number().int(),
    quantities: z.record(z.string(), QuantitySchema),
    point_count: z.number().int().gte(0),
    species: SpeciesDeclarationSchema.nullable().optional(),
  })
  .strict();

export const RunReportSchema = z
  .object({
    contract_version: z.string().optional(),
    run_id: z.string().min(1),
    request: RunRequestSchema,
    execution: RunExecutionSchema,
    provenance: RunProvenanceSchema,
    quantities: z.record(z.string(), QuantitySchema).optional(),
    trees: z.array(TreeReportSchema).optional(),
    limitations: z.array(z.string()).optional(),
  })
  .strict();

