"""Emit the shared fixture corpus.

The fixtures are committed as JSON and read by both the Python and the
TypeScript suites. This script exists so they can be regenerated deliberately
rather than hand-edited into disagreement with each other, and so that the
reason each invalid case is invalid is written down next to it.

Run from the package root:

    python tools/build_fixtures.py

Nothing here imports the contract models. The corpus is meant to be an
independent statement of the wire shape: if it were generated by serialising
the very models it is used to test, a model that serialised the wrong thing
would produce a fixture that agreed with it.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
VALID_DIR = PACKAGE_ROOT / "fixtures" / "valid"
INVALID_DIR = PACKAGE_ROOT / "fixtures" / "invalid"

FILE_SHA = "a" * 64
ANALYSED_SHA = "b" * 64
COMMIT = "c" * 40

PROTOCOL = {
    "id": "treeq-geometry-v1",
    "version": "1.0.0",
    "criteria_uri": "docs/ml/CAMEROON_EVIDENCE_CHAIN.md",
}

ALGORITHMS = {
    "ground_segmentation": "lowest_rank_grid",
    "height_normalization": "knn_idw",
    "chm": "max_z_morphology",
    "tree_segmentation": "watershed",
    "wood_leaf": "tlsep",
    "qsm": "ransac_dbh_maxz_height_taper_volume",
    "species": "stub",
    "allometric": "species_db_or_chave_fallback",
}


def request(**overrides: Any) -> dict[str, Any]:
    base = {
        "contract_version": "2.0.0",
        "request_id": "req-0001",
        "source": {
            "file_name": "plot_a.laz",
            "file_sha256": FILE_SHA,
            "byte_size": 10485760,
            "format": "laz",
            # Declared from the LAS header, not from the extension. A .laz
            # holding millimetres is the same extension as one holding metres.
            "length_unit": "metre",
            "length_unit_source": "file_header",
            "crs": {"authority": "EPSG", "code": "32632", "source": "file_header"},
            "vertical_datum": "EGM2008",
        },
        "species": {"scientific_name": "Tectona grandis", "source": "operator"},
        "wood_density": {
            "value_g_cm3": 0.655,
            "source": "dataset_metadata",
            "reference": "services/ml/data/species_db.csv, row Tectona grandis",
        },
        "wood_leaf_backend": "tlsep",
        "protocol": PROTOCOL,
        "max_points": 200000,
    }
    base.update(overrides)
    return base


def provenance(**overrides: Any) -> dict[str, Any]:
    base = {
        "pipeline_version": "0.4.0",
        "git_commit": COMMIT,
        "git_dirty": False,
        "algorithms": dict(ALGORITHMS),
        "wood_leaf_backend": "tlsep",
        "checkpoint_sha256": None,
        # Not the file hash. The file is 5,000,000 points; 200,000 of them
        # were measured, and this digest covers those 200,000 only.
        "analysed_points_sha256": ANALYSED_SHA,
        "n_source_points": 5000000,
        "n_analysed_points": 200000,
    }
    base.update(overrides)
    return base


def execution(status: str = "ok", **overrides: Any) -> dict[str, Any]:
    base = {
        "status": status,
        "started_at": "2026-09-13T02:15:00Z",
        "finished_at": "2026-09-13T02:17:42Z",
        "error_code": None,
        "error_message": None,
    }
    base.update(overrides)
    return base


def quantity(
    value: float | None,
    unit: str,
    status: str,
    *,
    depends_on: tuple[str, ...] = (),
    protocol: dict[str, Any] | None = None,
    unusable_reason: str | None = None,
    basis: str | None = None,
    sensitivity: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "value": value,
        "unit": unit,
        "status": status,
        "protocol": protocol,
        "depends_on": list(depends_on),
        "unusable_reason": unusable_reason,
        "basis": basis,
        "sensitivity": sensitivity,
    }


def accepted(value: float, unit: str, **kw: Any) -> dict[str, Any]:
    return quantity(value, unit, "accepted", protocol=PROTOCOL, **kw)


SENSITIVITY = {
    "low": 1102.4,
    "high": 1509.7,
    # Wood density only. Recomputed at the ends of the plausible density range
    # for this species; it is not a confidence interval and the contract
    # refuses any basis text that calls it one.
    "basis": (
        "CO2e recomputed at the ends of the plausible wood density range "
        "(0.55-0.75 g/cm3). Density assumption only: excludes measurement "
        "error and the allometric model being wrong."
    ),
}

PLOT_DENSITY = accepted(
    0.655,
    "g/cm3",
    basis="species_db.csv row for Tectona grandis; not measured on this plot",
)

#: A genuine zero. The plot really did exclude no segments, which is a
#: different statement from "this run did not record exclusions".
PLOT_EXCLUDED_ZERO = accepted(
    0.0,
    "count",
    basis="every detected segment was measured; this is a counted zero",
)


def healthy_tree(tree_id: int) -> dict[str, Any]:
    return {
        "tree_id": tree_id,
        "point_count": 48213,
        "species": {"scientific_name": "Tectona grandis", "source": "operator"},
        "quantities": {
            "dbh_cm": accepted(
                31.4, "cm", basis="RANSAC circle at 1.3 m, inlier ratio 0.94"
            ),
            "height_m": accepted(18.2, "m", basis="max z above normalised ground"),
            "agb_kg": accepted(
                412.6,
                "kg",
                depends_on=("dbh_cm", "height_m", "plot.wood_density_g_cm3"),
                basis="species-specific allometric equation",
            ),
            "bgb_kg": accepted(
                99.0,
                "kg",
                depends_on=("agb_kg",),
                basis="root-to-shoot 0.24, IPCC 2006",
            ),
            # AGB + BGB, matching what the legacy biomass_kg field has always
            # held. Named in full so it cannot be mistaken for AGB alone.
            "biomass_total_kg": accepted(
                511.6,
                "kg",
                depends_on=("agb_kg", "bgb_kg"),
                basis="above-ground plus below-ground",
            ),
            "co2eq_kg": accepted(
                1305.2,
                "kg",
                depends_on=("biomass_total_kg",),
                basis="carbon fraction 0.47, CO2e factor 44/12",
                sensitivity=SENSITIVITY,
            ),
        },
    }


def report(**overrides: Any) -> dict[str, Any]:
    base = {
        "contract_version": "2.0.0",
        "run_id": "run-0001",
        "request": request(),
        "execution": execution(),
        "provenance": provenance(),
        "quantities": {
            "wood_density_g_cm3": PLOT_DENSITY,
            "excluded_tree_count": PLOT_EXCLUDED_ZERO,
        },
        "trees": [healthy_tree(1)],
        "limitations": [
            "Geometry validated on 65 temperate and 61 tropical reference "
            "trees; this plot is neither.",
            "The species stage is a stub. Species here was declared by the "
            "operator, not classified.",
        ],
    }
    base.update(overrides)
    return base


def write(directory: Path, name: str, payload: dict[str, Any]) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
    (directory / f"{name}.json").write_text(text, encoding="utf-8", newline="\n")


def build_valid() -> dict[str, dict[str, Any]]:
    cases: dict[str, dict[str, Any]] = {}

    cases["accepted_single_tree"] = report()

    # Species unknown. The run still produces a mass, through the Chave
    # fallback on a generic density - but nothing derived from that assumption
    # may claim acceptance, so the chain below it is provisional.
    generic_density = quantity(
        0.6,
        "g/cm3",
        "provisional",
        basis="Chave 2014 pantropical default; no species was declared",
    )
    unknown = healthy_tree(1)
    unknown["species"] = None
    unknown["quantities"]["agb_kg"] = quantity(
        398.1,
        "kg",
        "provisional",
        depends_on=("dbh_cm", "height_m", "plot.wood_density_g_cm3"),
        basis="Chave 2014 pantropical, generic density",
    )
    for name in ("bgb_kg", "biomass_total_kg", "co2eq_kg"):
        downstream = dict(unknown["quantities"][name])
        downstream["status"] = "provisional"
        downstream["protocol"] = None
        unknown["quantities"][name] = downstream
    cases["species_unknown_chave_fallback"] = report(
        request=request(species=None, wood_density=None),
        quantities={
            "wood_density_g_cm3": generic_density,
            "excluded_tree_count": PLOT_EXCLUDED_ZERO,
        },
        trees=[unknown],
        limitations=[
            "No species was declared. Every mass below is a pantropical "
            "default, not a species-specific estimate."
        ],
    )

    # The QSM stage refused this stem, so there is no diameter. Everything
    # downstream carries no number at all rather than a zero.
    refused = healthy_tree(2)
    refused["quantities"]["dbh_cm"] = quantity(
        None,
        "cm",
        "unusable",
        unusable_reason="protocol_not_met",
        basis="RANSAC inlier ratio 0.11, below the 0.20 floor the fit requires",
    )
    for name in ("agb_kg", "bgb_kg", "biomass_total_kg", "co2eq_kg"):
        broken = dict(refused["quantities"][name])
        broken["value"] = None
        broken["status"] = "unusable"
        broken["protocol"] = None
        broken["sensitivity"] = None
        broken["unusable_reason"] = "dependency_unusable"
        broken["basis"] = "no usable diameter for this stem"
        refused["quantities"][name] = broken
    cases["unusable_from_refused_dependency"] = report(
        run_id="run-0002",
        quantities={
            "wood_density_g_cm3": PLOT_DENSITY,
            "excluded_tree_count": accepted(
                1.0, "count", basis="one segment failed the diameter fit"
            ),
        },
        trees=[refused],
    )

    # The run died. Nothing it half-computed is offered as a number.
    dead = healthy_tree(1)
    for name, q in list(dead["quantities"].items()):
        dead["quantities"][name] = quantity(
            None,
            q["unit"],
            "unusable",
            depends_on=tuple(q["depends_on"]),
            unusable_reason="execution_failed",
            basis="run aborted before this stage completed",
        )
    # The plot-level quantities stay in the document as unusable rather than
    # being dropped. A tree quantity still records what it WOULD have been
    # derived from, and a dependency name that points at nothing is the
    # "missing dependency" case dressed as an absence - the graph has to stay
    # resolvable so a reader can see the collapse reached all of it.
    dead_plot = {
        name: quantity(
            None,
            unit,
            "unusable",
            unusable_reason="execution_failed",
            basis="run aborted before this stage completed",
        )
        for name, unit in (("wood_density_g_cm3", "g/cm3"), ("excluded_tree_count", "count"))
    }
    cases["execution_failed_nothing_usable"] = report(
        run_id="run-0003",
        execution=execution(
            status="failed",
            error_code="POINT_CLOUD_UNREADABLE",
            error_message="laspy could not read the point records",
        ),
        quantities=dead_plot,
        trees=[dead],
        limitations=["The run failed; this document records only that."],
    )

    return cases


def build_invalid() -> dict[str, dict[str, Any]]:
    cases: dict[str, dict[str, Any]] = {}

    def case(name: str, error: str, contains: str, document: dict[str, Any]) -> None:
        cases[name] = {
            "__expect__": {"error": error, "contains": contains},
            "document": document,
        }

    # A number nobody may use is still a number once it is in the field, and it
    # will be summed by something.
    doc = report()
    doc["trees"][0]["quantities"]["dbh_cm"] = {
        "value": 0.0,
        "unit": "cm",
        "status": "unusable",
        "protocol": None,
        "depends_on": [],
        "unusable_reason": "protocol_not_met",
        "basis": None,
        "sensitivity": None,
    }
    case("unusable_carries_value", "schema", "must not carry a value", doc)

    doc = report()
    bare = dict(doc["trees"][0]["quantities"]["dbh_cm"])
    bare["protocol"] = None
    doc["trees"][0]["quantities"]["dbh_cm"] = bare
    case("accepted_without_protocol", "schema", "must name the protocol", doc)

    doc = report()
    sens = dict(SENSITIVITY)
    sens["basis"] = "95% confidence interval on the CO2e estimate"
    q = dict(doc["trees"][0]["quantities"]["co2eq_kg"])
    q["sensitivity"] = sens
    doc["trees"][0]["quantities"]["co2eq_kg"] = q
    case(
        "sensitivity_relabelled_as_confidence_interval",
        "schema",
        "confidence interval",
        doc,
    )

    doc = report(provenance=provenance(n_source_points=1000, n_analysed_points=5000))
    case("analysed_exceeds_source", "schema", "exceeds", doc)

    doc = report()
    doc["trees"][0]["quantities"]["dbh_cm"]["measured_by"] = "tape"
    case("unknown_field_rejected", "schema", "measured_by", doc)

    doc = report()
    doc["request"]["source"]["length_unit"] = "parsec"
    case("unknown_length_unit", "schema", "length_unit", doc)

    # The property this enum exists to make unwritable.
    doc = report()
    doc["request"]["species"] = {
        "scientific_name": "Tectona grandis",
        "source": "filename",
    }
    case("species_guessed_from_filename", "schema", "source", doc)

    doc = report()
    plot = dict(doc["quantities"]["wood_density_g_cm3"])
    plot["status"] = "provisional"
    plot["protocol"] = None
    doc["quantities"]["wood_density_g_cm3"] = plot
    case(
        "accepted_from_provisional_dependency",
        "semantic",
        "accepted_from_provisional",
        doc,
    )

    doc = report()
    plot = dict(doc["quantities"]["wood_density_g_cm3"])
    plot["value"] = None
    plot["status"] = "unusable"
    plot["protocol"] = None
    plot["unusable_reason"] = "dependency_missing"
    doc["quantities"]["wood_density_g_cm3"] = plot
    case("usable_from_unusable_dependency", "semantic", "usable_from_unusable", doc)

    doc = report()
    q = dict(doc["trees"][0]["quantities"]["agb_kg"])
    q["depends_on"] = ["dbh_cm", "height_m", "plot.crown_volume_m3"]
    doc["trees"][0]["quantities"]["agb_kg"] = q
    case("unresolved_dependency", "semantic", "unresolved_dependency", doc)

    doc = report(
        execution=execution(
            status="failed",
            error_code="POINT_CLOUD_UNREADABLE",
            error_message="laspy could not read the point records",
        )
    )
    case("accepted_after_execution_failed", "semantic", "accepted_after_failure", doc)

    doc = report()
    q = dict(doc["trees"][0]["quantities"]["dbh_cm"])
    q["depends_on"] = ["co2eq_kg"]
    doc["trees"][0]["quantities"]["dbh_cm"] = q
    case("dependency_cycle", "semantic", "dependency_cycle", doc)

    return cases


def main() -> int:
    for name, payload in build_valid().items():
        write(VALID_DIR, name, payload)
    for name, payload in build_invalid().items():
        write(INVALID_DIR, name, payload)
    print(
        f"wrote {len(build_valid())} valid and {len(build_invalid())} invalid fixtures"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
