"""Generate JSON Schema, TypeScript types and Zod validators from the models.

The Python models are the source of truth. Everything this script writes is
derived, and `--check` fails when what is on disk no longer matches what the
models would produce - which is the only thing standing between a field added
in Python and a web client that silently never learned about it.

    python tools/generate_contract.py            # write
    python tools/generate_contract.py --check    # CI: exit 1 on drift

The emitter handles the subset of JSON Schema that pydantic actually produces
for these models: objects with `additionalProperties: false`, string enums,
`anyOf` unions used for optionals, arrays, and `additionalProperties` maps.
It deliberately does not try to be a general JSON Schema compiler - an input
it does not understand raises rather than emitting something plausible.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "python"))

from treeq_run_contract.models import RunReport, RunRequest  # noqa: E402
from treeq_run_contract.version import CONTRACT_VERSION  # noqa: E402

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = PACKAGE_ROOT / "schema"
TS_DIR = PACKAGE_ROOT / "typescript" / "src"

BANNER = (
    "// GENERATED by tools/generate_contract.py from the pydantic models in\n"
    "// python/treeq_run_contract/. Do not edit by hand: CI runs\n"
    "// `python tools/generate_contract.py --check` and fails on drift.\n"
    f"// Contract version {CONTRACT_VERSION}.\n"
)


def _fail(message: str) -> None:
    raise NotImplementedError(
        f"{message}. The emitter refuses shapes it does not understand rather "
        "than guessing at a type the models did not ask for."
    )


def ts_doc(text: str | None, indent: str = "") -> str:
    """Carry a model's docstring into the generated TypeScript.

    The rules in those docstrings are the reason the fields are shaped the way
    they are. Dropping them on the way out would leave a web developer reading
    field names with none of the reasoning attached.
    """
    if not text:
        return ""
    lines = [line.rstrip() for line in text.strip().splitlines()]
    body = "\n".join(f"{indent} * {line}".rstrip() for line in lines)
    return f"{indent}/**\n{body}\n{indent} */\n"


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def is_nullable(schema: dict[str, Any]) -> tuple[bool, dict[str, Any]]:
    """Split pydantic's `anyOf: [X, null]` optional encoding."""
    options = schema.get("anyOf")
    if not options:
        return False, schema
    non_null = [o for o in options if o.get("type") != "null"]
    nullable = len(non_null) != len(options)
    if len(non_null) == 1:
        return nullable, non_null[0]
    if not non_null:
        _fail("an anyOf of nothing but null")
    return nullable, {"anyOf": non_null}


def ts_type(schema: dict[str, Any]) -> str:
    nullable, inner = is_nullable(schema)
    rendered = _ts_type_inner(inner)
    return f"{rendered} | null" if nullable else rendered


def _ts_type_inner(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "anyOf" in schema:
        return " | ".join(_ts_type_inner(o) for o in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"number", "integer"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        items = schema.get("items")
        if items is None:
            _fail("an array with no item schema")
        return f"ReadonlyArray<{ts_type(items)}>"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Readonly<Record<string, {ts_type(extra)}>>"
        return "Readonly<Record<string, unknown>>"
    _fail(f"a schema with no type this emitter knows: {sorted(schema)}")
    raise AssertionError("unreachable")


def zod_expr(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    nullable, inner = is_nullable(schema)
    rendered = _zod_expr_inner(inner, defs)
    return f"{rendered}.nullable()" if nullable else rendered


def _zod_expr_inner(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"{ref_name(schema['$ref'])}Schema"
    if "anyOf" in schema:
        parts = ", ".join(_zod_expr_inner(o, defs) for o in schema["anyOf"])
        return f"z.union([{parts}])"
    if "enum" in schema:
        values = ", ".join(json.dumps(v) for v in schema["enum"])
        return f"z.enum([{values}])"
    kind = schema.get("type")
    if kind == "string":
        expr = "z.string()"
        if "minLength" in schema:
            expr += f".min({schema['minLength']})"
        if "maxLength" in schema:
            expr += f".max({schema['maxLength']})"
        if "pattern" in schema:
            expr += f".regex(new RegExp({json.dumps(schema['pattern'])}))"
        return expr
    if kind in {"number", "integer"}:
        expr = "z.number()"
        if kind == "integer":
            expr += ".int()"
        if "minimum" in schema:
            expr += f".gte({schema['minimum']})"
        if "maximum" in schema:
            expr += f".lte({schema['maximum']})"
        if "exclusiveMinimum" in schema:
            expr += f".gt({schema['exclusiveMinimum']})"
        if "exclusiveMaximum" in schema:
            expr += f".lt({schema['exclusiveMaximum']})"
        return expr
    if kind == "boolean":
        return "z.boolean()"
    if kind == "null":
        return "z.null()"
    if kind == "array":
        items = schema.get("items")
        if items is None:
            _fail("an array with no item schema")
        return f"z.array({zod_expr(items, defs)})"
    if kind == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"z.record(z.string(), {zod_expr(extra, defs)})"
        return "z.record(z.string(), z.unknown())"
    _fail(f"a schema with no type this emitter knows: {sorted(schema)}")
    raise AssertionError("unreachable")


def order_defs(defs: dict[str, Any]) -> list[str]:
    """Emit definitions after the ones they reference.

    Zod schemas are `const` bindings, so a schema that names another before it
    is declared is a runtime error rather than a type error.
    """
    emitted: list[str] = []
    seen: set[str] = set()

    def dependencies(schema: Any) -> set[str]:
        found: set[str] = set()
        if isinstance(schema, dict):
            if "$ref" in schema:
                found.add(ref_name(schema["$ref"]))
            for value in schema.values():
                found |= dependencies(value)
        elif isinstance(schema, list):
            for value in schema:
                found |= dependencies(value)
        return found

    def visit(name: str, trail: tuple[str, ...]) -> None:
        if name in seen:
            return
        if name in trail:
            raise NotImplementedError(
                f"the models form a reference cycle through {' -> '.join((*trail, name))}; "
                "Zod would need z.lazy() and this emitter does not write it"
            )
        for dep in sorted(dependencies(defs[name])):
            if dep in defs:
                visit(dep, (*trail, name))
        seen.add(name)
        emitted.append(name)

    for name in sorted(defs):
        visit(name, ())
    return emitted


def render_types(defs: dict[str, Any], roots: dict[str, Any]) -> str:
    out = [BANNER, "\n"]
    for name in order_defs(defs):
        schema = defs[name]
        out.append(render_one_type(name, schema))
    for name, schema in roots.items():
        out.append(render_one_type(name, schema))
    return "".join(out)


def render_one_type(name: str, schema: dict[str, Any]) -> str:
    doc = ts_doc(schema.get("description"))
    if "enum" in schema:
        values = "\n".join(f"  | {json.dumps(v)}" for v in schema["enum"])
        return f"{doc}export type {name} =\n{values};\n\n"
    if schema.get("type") != "object":
        _fail(f"a top-level definition {name} that is neither object nor enum")
    required = set(schema.get("required", ()))
    lines = [f"{doc}export interface {name} {{"]
    for field, field_schema in schema.get("properties", {}).items():
        field_doc = ts_doc(field_schema.get("description"), indent="  ")
        optional = "" if field in required else "?"
        lines.append(f"{field_doc}  readonly {field}{optional}: {ts_type(field_schema)};")
    lines.append("}\n\n")
    return "\n".join(lines)


def render_zod(defs: dict[str, Any], roots: dict[str, Any]) -> str:
    out = [BANNER, '\nimport { z } from "zod";\n\n']
    for name in order_defs(defs):
        out.append(render_one_zod(name, defs[name], defs))
    for name, schema in roots.items():
        out.append(render_one_zod(name, schema, defs))
    return "".join(out)


def render_one_zod(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "enum" in schema:
        values = ", ".join(json.dumps(v) for v in schema["enum"])
        return f"export const {name}Schema = z.enum([{values}]);\n\n"
    required = set(schema.get("required", ()))
    lines = [f"export const {name}Schema = z"]
    lines.append("  .object({")
    for field, field_schema in schema.get("properties", {}).items():
        expr = zod_expr(field_schema, defs)
        if field not in required:
            expr += ".optional()"
        lines.append(f"    {field}: {expr},")
    # `additionalProperties: false` on every contract model is the point: a
    # producer that grows a field without bumping the contract must fail here
    # rather than have the extra key quietly dropped.
    lines.append("  })")
    lines.append("  .strict();")
    lines.append("")
    lines.append("")
    return "\n".join(lines)


def render_index(root_names: list[str]) -> str:
    exports = "\n".join(f'export * from "./{module}.js";' for module in ("types", "zod"))
    names = ", ".join(root_names)
    return (
        f"{BANNER}\n{exports}\n\n"
        "// The relational rules live beside the generated shapes because JSON\n"
        "// Schema cannot express them; semantics.ts mirrors semantics.py and the\n"
        "// shared fixture corpus is what proves the two agree.\n"
        'export * from "./semantics.js";\n\n'
        f"// Root documents: {names}\n"
        f'export const CONTRACT_VERSION = "{CONTRACT_VERSION}";\n'
    )


def build() -> dict[Path, str]:
    """Return every generated file's path and its exact intended content."""
    request_schema = RunRequest.model_json_schema(ref_template="#/$defs/{model}")
    report_schema = RunReport.model_json_schema(ref_template="#/$defs/{model}")

    defs = dict(report_schema.pop("$defs", {}))
    request_schema.pop("$defs", None)
    # RunRequest is reachable from RunReport, so it is already a definition.
    # Emitting it a second time as a root would declare the same name twice.
    defs.pop("RunReport", None)
    roots = {"RunReport": report_schema}

    files: dict[Path, str] = {}
    for name, schema in (
        ("run-request", RunRequest.model_json_schema()),
        ("run-report", RunReport.model_json_schema()),
    ):
        document = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": f"https://treeq.dev/schema/{CONTRACT_VERSION}/{name}.schema.json",
            **schema,
        }
        files[SCHEMA_DIR / f"{name}.schema.json"] = (
            json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        )

    files[TS_DIR / "types.ts"] = render_types(defs, roots)
    files[TS_DIR / "zod.ts"] = render_zod(defs, roots)
    files[TS_DIR / "index.ts"] = render_index(sorted(roots))
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if any generated file is missing or stale",
    )
    args = parser.parse_args()

    files = build()
    if not args.check:
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {len(files)} generated files")
        return 0

    drifted: list[str] = []
    for path, content in files.items():
        relative = path.relative_to(PACKAGE_ROOT)
        if not path.is_file():
            drifted.append(f"{relative}: missing")
        elif path.read_text(encoding="utf-8") != content:
            drifted.append(f"{relative}: stale")
    if drifted:
        print("generated files do not match the models:", file=sys.stderr)
        for line in drifted:
            print(f"  {line}", file=sys.stderr)
        print(
            "\nrun: python tools/generate_contract.py  (from packages/run-contract)",
            file=sys.stderr,
        )
        return 1
    print(f"{len(files)} generated files match the models")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
